# Generated by Django 4.1.5 on 2023-01-21 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_answer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='Answer2',
        ),
        migrations.AlterField(
            model_name='answer2',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question'),
        ),
    ]
